[package]
name = "gstreamer-tutorial-1-hello-world"
version = "0.1.0"
authors = ["rubenrua <rubenrua@teltek.es>"]

[dependencies.gstreamer]
git = "https://github.com/luisbg/gstreamer1.0-rs.git"
branch = "rustfest"
